---
- name: Set up Ubuntu 24.04 server
  hosts: webserver
  become: yes
  vars_files:
    - vars/secret.yml

  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - ufw
        state: present

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create new user
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash

    - name: Add new user to Docker group
      user:
        name: "{{ new_user }}"
        groups: docker
        append: yes

    - name: Allow new user to use sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ new_user }}"
        line: "{{ new_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Set up SSH keys for new user
      authorized_key:
        user: "{{ new_user }}"
        key: "{{ item }}"
      loop: "{{ ssh_public_keys }}"

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      notify: Restart SSH

    - name: Allow SSH for new user
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^AllowUsers"
        line: "AllowUsers {{ new_user }}"
      notify: Restart SSH

    - name: Configure UFW
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "22"
        - "80"
        - "443"

    - name: Enable UFW
      ufw:
        state: enabled

    # TODO add to install postgresql
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Set up automatic security updates
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable automatic security updates
      copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Enable fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Restart Docker
      service:
        name: docker
        state: restarted

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
