apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-server
  template:
    metadata:
      labels:
        app: cv-server
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  selector:
    app: cv-server
  ports:
    - port: 80
      targetPort: 80
