apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../base
namePrefix: cv-
namespace: default
commonLabels:
  app: cv-server
images:
  - name: placeholder-image
    newName: behaqosimi/cv-image:003ba5737fceb017f09b06fe0c5ba611a598a665
patchesStrategicMerge:
  - |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: app-ingress
    spec:
      tls:
      - hosts:
        - bkasymov.online
        secretName: cv-tls
      rules:
      - host: bkasymov.online
        http:
          paths:
          - path: /cv
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
