name: Build and Deploy CV

on:
  push:
    branches:
    - main
    paths:
    - 'apps/cv/CV.pdf'
    - 'apps/cv/Dockerfile'
  workflow_dispatch:

env:
  DOCKER_IMAGE: behaqosimi/cv-image

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: apps/cv/Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    - name: Update Kubernetes manifests
      run: |
        sed -i 's|newName: .*|newName: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}|' apps/cv/manifests/overlays/cv/kustomization.yaml

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add apps/cv/manifests/overlays/cv/kustomization.yaml
        git commit -m "Update image to ${{ github.sha }}" || exit 0
        git push
